# K-M (kint & merge) approach, see https://bookdown.org/yihui/bookdown/new-session.html
new_session: yes


book_filename: "standard_inputs"
delete_merged_file: true
output_dir: "_book"

# language:
#   ui:
#     chapter_name: "Chapter "

before_chapter_script: "_common.R"

rmd_files: [
  "index.qmd",

  "foreword.qmd",  
  "introduction.qmd",
  "conversions.qmd",
  "geographical_areas.qmd",
  
  # Part: Traffic and capacity
  "traffic_and_capacity_PART.qmd",
  "air_traffic_statistics_and_forecasts.qmd",
  "medium-term_capacity_planning.qmd",
  "number_of_ifr_flights.qmd",
  "air_traffic_delay.qmd",
  "flow_management_delay.qmd",

  #  Part: Environment
  "environment_PART.qmd",
  "rate_of_fuel_burn.qmd",
  "amount_of_emissions_released_by_fuel_burn.qmd",
  "cost_of_emissions.qmd",
  "cost_of_noise.qmd",
  
  # Part: Airspace users
  "airspace_users_PART.qmd",
  "aircraft_operating_costs.qmd",
  "average_number_of_passengers_per_movement.qmd",  
  "cancellation_cost.qmd",
  "operational_cancellation_rate.qmd",
  "cost_of_delay.qmd",
  "cost_of_diversion.qmd",
  "turnaround_time.qmd",
  "ifr_average_flight_distance_and_flight_duration.qmd",
  "ifr_flight_information_per_market_segment.qmd",
  "distance_flown_by_charging_zone.qmd",
  "load_factor-cargo.qmd",
  "load_factor-passengers.qmd",
  "cost_of_aviation_fuel.qmd",
  "value_of_an_average_passenger_flight.qmd",
  "fleet_age.qmd",
  "fleet_size.qmd",
  "fleet_cns_capability.qmd",
  
  # Part: ATM
  "atm_PART.qmd",
  "en_route_ans_costs.qmd",
  "route_charge_share_per_market_segment.qmd",
  "ansps_employment_costs.qmd",
  "asset_life.qmd",
  "atm_cost-effectiveness_indicators.qmd",
  "atm_operational_units.qmd",
  "cns_infrastructure.qmd",
  "pbn_and_precision_approach_procedures.qmd",
  
  # Part: Airport
  "airport_PART.qmd",
  "airport_classification.qmd",
  "taxiing_times.qmd",
  
  # Part: Drones
  "drones_PART.qmd",
  "investment_in_u-space.qmd",
  "drone_fleet.qmd",
  
  # Part: Passengers
  "passengers_PART.qmd",
  "purpose_of_passenger_travel.qmd",
  "passenger_value_of_time.qmd",
  
  # Part: Safety 
  "safety_PART.qmd",
  "accident-incident_statistics.qmd",
  "value_of_a_statistical_life-vsl.qmd",
  "value_of_a_statistical_injury.qmd",

  # Part: Financial values
  "financial_values_PART.qmd",
  "discount_rate.qmd",
  "exchange_rate.qmd",
  
  # Part: General information
  "abbreviations.qmd",
  
  "references.qmd",
  "annexes.qmd",
  "data.qmd",

]
