project:
  type: book
  output-dir: _book

execute:
  freeze: auto
  echo: false
  warning: false


bibliography: "bibliography.bib"
csl: media/ieee-with-url.csl
link-citations: true
cover-image: cover.png


format:
  html:
    css:
      - media/style.css
    theme:
      - default
    #   - custom.scss
    code-link: true
    cover-image: media/cover.png
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: '^(?:http:|https:)\/\/ansperformance\.eu\/|^(?:http:|https:)\/\/.*standard-inputs\.netlify\.app\/'
    include-in-header:
      - media/fontawesome.html
      # UNCOMMENT for activating GA
      - media/analytics.html
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    documentclass: book
    papersize: a4
    fontsize: 11pt
    links-as-notes: true

book:
  title: "EUROCONTROL Standard Inputs for Economic Analyses"
  author:
    - "EUROCONTROL Business Cases team"
  date: "2022-12-13"
  description: "This document provides values for data items commonly used in economic analyses, especially cost-benefit analyses. Each standard input is presented together with details of the sources and a discussion of the applicability and use of the values. The values have been compiled from publicly available documents. They are often average values and may not be appropriate in all circumstances."
  search: true
  repo-url: https://github.com/euctrl-pru/standard_inputs
  downloads: [pdf]
  sharing: [twitter]
  output-file: "standard_inputs"
  site-url: "https://eurocontrol.int/"
  chapters:
    - "index.qmd"
 
    - "foreword.qmd"  
    - "introduction.qmd"
    - "conversions.qmd"
    - "geographical_areas.qmd"
    
    - part: "Traffic and capacity"
      chapters:
        - "air_traffic_statistics_and_forecasts.qmd"
        - "medium-term_capacity_planning.qmd"
        - "number_of_ifr_flights.qmd"
        - "air_traffic_delay.qmd"
        # - "transit_time.qmd"
    
    - part: "Environment"
      chapters:
        - "rate_of_fuel_burn.qmd"
        - "amount_of_emissions_released_by_fuel_burn.qmd"
        - "cost_of_emissions.qmd"
        - "cost_of_noise.qmd"
        - "shadow_cost_of_carbon.qmd"
        - "proportion_of_saf.qmd"
    
    - part: "Airspace Users"
      chapters:
        - "aircraft_operating_costs.qmd"
        - "average_number_of_passengers.qmd"  
        - "cancellation_cost.qmd"
        - "operational_cancellation_rate.qmd"
        - "cost_of_delay.qmd"
        - "cost_of_diversion.qmd"
        - "turnaround_time.qmd"
        - "ifr_average_flight_distance_and_flight_duration.qmd"
        - "ifr_flight_information_per_market_segment.qmd"
        - "distance_flown_by_charging_zone.qmd"
        - "load_factor-cargo.qmd"
        - "load_factor-passengers.qmd"
        - "cost_of_aviation_fuel.qmd"
        - "value_of_an_average_passenger_flight.qmd"
        - "fleet_age.qmd"
        - "fleet_size.qmd"
        - "fleet_cns_capability.qmd"
    
    - part: "ATM"
      chapters:
        - "en_route_ans_costs.qmd"
        - "route_charge_share_per_market_segment.qmd"
        - "ansps_employment_costs.qmd"
        - "asset_life.qmd"
        - "atm_cost-effectiveness_indicators.qmd"
        - "atm_operational_units.qmd"
        - "cns_infrastructure.qmd"
        - "pbn_and_precision_approach_procedures.qmd"
    
    - part: "Airports"
      chapters:
        - "airport_classification.qmd"
        - "taxiing_times.qmd"
     
    - part: "Drones"
      chapters:
        - "investment_in_u-space.qmd"
        - "drone_fleet.qmd"
     
    - part: "Passengers"
      chapters:
        - "purpose_of_passenger_travel.qmd"
        - "passenger_value_of_time.qmd"
     
    - part: "Safety"
      chapters:
        - "accident-incident_statistics.qmd"
        - "value_of_a_statistical_life-vsl.qmd"
        - "value_of_a_statistical_injury.qmd"
     
    - part: "Financial values"
      chapters:
        - "discount_rate.qmd"
        - "exchange_rate.qmd"
     
    - part: "General information"
      chapters:
        - "abbreviations.qmd"
        # - "references.qmd"
    # - "annexes.qmd"
    # - "data.qmd"

  navbar:
    background: light
    search: false
    title: false
    logo: "media/EUROCONTROL-logo-standard-rgb.svg"
    left:
      - text: "AIU Home"
        menu:
          - text: "**Home**"
            icon: "house-fill"
            href: "https://ansperformance.eu"
            # ---
          - text: "<i class='fas fa-plane-departure'></i> **Traffic**"
            href: "https://ansperformance.eu/traffic/"

          - text: "</i> Daily Traffic Dashboard</i>"
            icon: "arrow-return-right"
            href: "https://www.eurocontrol.int/Economics/DailyTrafficVariation-States.html"

          - text: "Traffic Forecast"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/traffic/statfor/"
            # ---
          - text: "<i class='fas fa-leaf'></i> **Efficiency & Environment**"
            href: "https://ansperformance.eu/efficiency/"
          - text: "CO<sub>2</sub> emissions"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/efficiency/emissions/"
          - text: "Horizontal Flight Efficiency"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/efficiency/hfe/"

          - text: "Vertical Flight Efficiency"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/efficiency/vfe/"

          - text: "Terminal Holdings"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/efficiency/asma/"

          - text: "Taxi-out"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/efficiency/taxiout/"

           # ---
          - text: "<i class='fas fa-euro-sign'></i> **Economics**"
            href: "https://ansperformance.eu/economics/"

          - text: "Service Units"
            icon: "arrow-return-right"
            href: "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html"

          - text: "Unit Rates and Costs"
            icon: "arrow-return-right"
            href: "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteUnitRates.html"

          - text: "ATM Cost Effectiveness"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/ACE/"

          - text: "ANSPs Financial Situation"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/economics/finance/"

          - text: "CBA"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/economics/cba/"

            # ---
          - text: "<i class='fas fa-user-friends'></i> **Stakeholder views**"
            href: "https://ansperformance.eu/dashboard/stakeholder/"

          - text: "Airport View"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/airport/"

          - text: "ANSP View"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/ansp/"

          - text: "FAB View"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/dashboard/stakeholder/fab/"

          - text: "State View"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/dashboard/stakeholder/state/"

            # ---
          - text: "<i class='fas fa-book'></i> **Publications**"
            href: "https://ansperformance.eu/publications/"

          - text: "Data"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/data/"

            # ---
          - text: "<i class='fas fa-hands-helping'></i> **Reference**"
            href: "https://ansperformance.eu/reference/"

            # ---
          - text: "<i class='fas fa-external-link-alt'></i> **External**"

          - text: "Single European Sky Portal"
            icon: "arrow-return-right"
            href: "https://www.eurocontrol.int/prudata/dashboard/"

          - text: "ICAO GANP"
            icon: "arrow-return-right"
            href: "https://www4.icao.int/ganpportal/"

      - text: "About"
        menu:
          - text: "About the PRC"
            href: "https://ansperformance.eu/about/prc/"

          - text: "About the PRU"
            href: "https://ansperformance.eu/about/us/"

          - text: "Release notes"
            href: "https://ansperformance.eu/post/"

          - text: "Disclaimer"
            href: "https://ansperformance.eu/about/disclaimer/"

      - text: "Areas"
        menu:
          - text: "Traffic"
            href: "https://ansperformance.eu/traffic/"

          - text: "Capacity & delays"
            href: "https://ansperformance.eu/capacity/"

          - text: "Efficiency & environment"
            href: "https://ansperformance.eu/efficiency/"

          - text: "Economics"
            href: "https://ansperformance.eu/economics/"

      - text: "Views"
        menu:
          - text: "Airports"
            href: "https://ansperformance.eu/dashboard/stakeholder/airport/"

          - text: "Air Navigation Service Provider"
            href: "https://ansperformance.eu/ansp/"

          - text: "Functional Airspace Block"
            href: "https://ansperformance.eu/fab/"

          - text: "State"
            href: "https://ansperformance.eu/dashboard/stakeholder/state/"

      - text: "Publications"
        href: "https://ansperformance.eu/publications/"

      - text: "Reference"
        menu:
          - text: "Data downloads"
            href: "https://ansperformance.eu/data/"

          - text: "Definitions"
            href: "https://ansperformance.eu/definition/"

          - text: "Methodology"
            href: "https://ansperformance.eu/methodology/"

          - text: "Acronyms"
            href: "https://ansperformance.eu/acronym/"

          - text: "Bibliography"
            href: "https://ansperformance.eu/bibliography/"

          - text: "---"

          - text: "<i class='fas fa-xs fa-external-link-alt'></i> ICAO GANP"
            href: "https://www4.icao.int/ganpportal/"

      - text: "SES"
        menu:
          - text: "<i class='fas fa-xs fa-external-link-alt'></i> Single European Sky (SES) Portal"
            href: "https://www.eurocontrol.int/prudata/dashboard/"

