# Amount of emissions released by fuel burn

## Definition
Amount (mass) of emissions released by the combustion of aviation fuel.

## EUROCONTROL recommended sources

Value
:   
    ```{r, emissions-per-kg}
    library(gt)
    library(magrittr)
    library(tibble)
    tribble(
      ~ "gas", ~ "amount",
      "CO2", "3.15 kg",
      "H2O", "1.237 kg",
      "SO2","0.00084 kg"
    ) %>% 
      gt() %>% 
        cols_label(
        gas = "Emissions",
        amount = md("Amount emitted<br>(per kg of fuel burned)")
      ) %>% 
      fmt_markdown(columns = TRUE)
    ```

Source
:   EUROCONTROL (2018) – “European Aviation Fuel Burn and Emissions Inventory
    System for the European Environment Agency”         
    https://www.eurocontrol.int/publication/european-aviation-fuel-burn-and-emissions-inventory-system-feis-european-environment


## Other possible sources

Source 1
:   European Environment Agency (2017) “EMEP/EEA air pollutant emission
    inventory guidebook – 2019” <br>
    https://www.eea.europa.eu/publications/emep-eea-guidebook-2019
    <br>
    Values specific to aviation are available in Part B: sectoral guidance
    chapters/1. Energy/1.A. Combustion/1.A.3.a Aviation <br>
    https://www.eea.europa.eu/publications/emep-eea-guidebook-2019/part-b-sectoral-guidance-chapters/1-energy/1-a-combustion/1-a-3-a-aviation/view


Description 1
:   The Emission Inventory Guidebook gives values for emission factors
    (for $CO_2$, $CH_4$, $N_2O$, $NO_x$, $CO$, NMVOC, $SO_2$ and PM2.5) and
    fuel consumption in different phases of flight – including taxiing –
    for different aircraft types, using three different levels of accuracy and
    complexity.
    In the table, the emission factors for the “Very Simple” (called Tier 1)
    methodology are given on a representative aircraft basis, using jet
    kerosene as fuel.


Source 2
:   ICAO Aircraft Engine Emissions Databank
    (for turbojet and turbofan Aircraft with a static thrust greater than
    26.7 kilonewtons), August 2020<br>
    https://www.easa.europa.eu/domains/environment/icao-aircraft-engine-emissions-databank
    
Description 2
:   This Databank contains information on exhaust emissions only for those
    aircraft engines which have entered production.
    The information was provided by engine manufacturers and collected by
    the International Civil Aviation Organization (ICAO).
    The European Aviation Safety Agency (EASA) hosts this Databank on behalf
    of ICAO.

Source 3
:   FOI, Swedish Defence Research Agency
    <br>(for turboprop aircraft) 
    <br>https://www.foi.se/en/our-knowledge/aeronautics-and-air-combat-simulation/fois-confidential-database-for-turboprop-engine-emissions.html

Description 3
:   FOI is the keeper of a confidential database of emission indices (EI) of
    $NO_x$, $HC$ and $CO$, with corresponding fuel flows for turboprop engines.
    Datasheets have been supplied by the turboprop engine manufacturers,
    originally for the purposes of calculating emissions-related landing charges.
    <br>
    The data are presented in the same format as in the ICAO (International
    Civil Aviation Organization) Engine Emissions Database for jet engines, but
    have not been endorsed by ICAO in a certification process.
    It should be noted that the data contain many inaccuracies, resulting
    primarily from the unregulated test methodologies.
    The data is, however, considered to be the best available, and may be used
    for emissions inventories, emissions-related landing charges, etc.
    <br>
    The data are available on request.


Source 4
:   Swiss Federal Office of Civil Aviation, FOCA – Aircraft Engine Emissions
    <br>(for piston engine aircraft, helicopters) 
    <br>https://www.bazl.admin.ch/bazl/en/home/specialists/regulations-and-guidelines/environment/pollutant-emissions/aircraft-engine-emissions.html

Description 4
:   The Swiss FOCA has developed a measurement and calculation methodology for
    aircraft piston engine emissions in order to improve aviation emission
    inventories.


## Related standard inputs
[Rate of fuel burn], [cost of emissions] and
[IFR flight information per market segment].


## Comments

The Committee on Aviation Environmental Protection (CAEP), a technical committee
of the ICAO Council, recommends the use a conversion factor of 3.16 g of $CO_2$
per g of Jet A.
The 3.16 value can be found in ICAO Doc 9889, 1st edition, 2011, and other
documents.

However, in Europe, as early as 2009, Commission Decision 2009/339/EC indicated
an emission factor of 3.15 for the mass conversion from Jet A to CO2.
Commission Implementing Regulation (EU) 2018/2066 of 19 December 2018
(on the monitoring and reporting of greenhouse gas emissions),
which integrates the Carbon Offsetting and Reduction Scheme for International
Aviation (CORSIA) in the Emission Trading Scheme (ETS), applicable since
1 January 2019, for the period after January 2021, now recommends, for the time
being, that factor 3.15 for Jet A fuel is still to be used in Europe for the
ETS and also for CORSIA.

In view of the above, emission factor 3.15 should continue to be used in
SESAR 2020, for the sake of internal consistency within the programme, and
at least unless the EU ETS decides to move to 3.16.
Nevertheless, factor 3.16 should be used when the evaluation concerns
comparisons with studies carried out within the ICAO framework or using
the factor recommended by ICAO, in order to ensure external consistency.
[Extracted from SESAR 2020 – Environment Impact Assessment Guidance 
Guidance Del: 4.0.080]
