# ATM cost-effectiveness indicators {#sec-atm-cost-effectiveness-indicators}

## EUROCONTROL recommended values

This section considers some key performance indicators of cost-effectiveness and 
productivity for the Air Navigation Services Providers (ANSP) in the EUROCONTROL area.

The table below shows the trends in European system averages for the years 2015 through 2020.

```{r}
#| label: tbl-atm-cost-effectiveness
#| tbl-cap: ANSP cost-effectiveness and productivity indicators

library(readxl)
library(dplyr)
library(gt)

read_xlsx("data/atm_cost_effectiveness.xlsx") %>% 
  gt() %>% 
  cols_label(
    year = "Year",
    productivity = "ATCO-hour productivity",
    empl_cost = "Employment cost per ATCO hour",
    ratio = "Support staff ratio"
  ) %>% 
cols_align(
  align = "right",
  columns = productivity:ratio
) %>% 
  cols_align(
  align = "left",
  columns = year
) %>% 
  fmt_currency(
    currency = "EUR",
    columns = empl_cost,
    decimals = 2
  ) %>% 
  fmt_number(
    columns = ratio,
    decimals = 2
  ) %>% 
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "year"
    )
  ) %>% 
   tab_footnote(
    footnote = "Unit: composite flight-hours per ATCO-hour",
    locations = cells_column_labels(
      column = productivity
    )
  ) %>% 
  tab_footnote(
    footnote = "Unit: euro per ATCO-hour",
    locations = cells_column_labels(
      column = empl_cost
    )
  ) %>% 
  tab_footnote(
    footnote = "Unit: gate-to-gate ANS staff to ATCOs in OPS",
    locations = cells_column_labels(
      column = ratio
    )
  ) %>% 
  tab_options(
    table.width = pct(100)
   ) %>% 
   cols_width(
    year ~ px(40),
    productivity ~ px(120),
    empl_cost ~ px(120),
    ratio ~ px(120)
  ) %>% 
  tab_options(
    column_labels.font.weight = "bold"
  ) %>% 
  tab_options(
    column_labels.font.weight = "bold"
  ) %>% 
tab_source_note(
  source_note = md("*Source: [EUROCONTROL (2022), ATM cost-effectiveness (ACE) benchmarking report for 2020 with 2021-2024 outlook](https://ansperformance.eu/publications/prc/ace/)*")
)
```

## Description

The ACE benchmarking reports comprise data about and analysis of cost-effectiveness 
and productivity for the ANSPs in EUROCONTROL’s Member States. The key performance
drivers of cost-effectiveness are:

* Productivity

* Employment costs

* Support costs, comprising costs for non-ATCOs in OPS employment, non-staff 
operating costs, exceptional costs, depreciation and capital-related costs

The 2020 key performance drivers of financial cost-effectiveness for each ANSP 
are summarised in Figure 0.4 of the source document [@ace2020]. There is a wide variation
in each of the components:

* ATCO productivity ranges from 0.08 to 1.29 (figure 2.8 of the source document)

* Employment costs per ATCO-hour vary from a minimum of €16 to a maximum of €345 
per ATCO-hour in purchasing power parity terms (figure 2.10 of the source document)

* Support cost ratios as a component of gate-to-gate cost-effectiveness vary 
from 1.9 to 7.9 in 2020 (ratio G2G ANS staff/ATCOs in OPS in Annex 5; Table 0.5 
of the source document

:::{.callout-note}
The employment costs above refer to gate-to-gate cost, i.e. en route and terminal
costs, and are expressed in nominal prices.
:::

## Related inputs

@sec-ansp-employment-cost [ANSP employment cost](#sec-ansp-employment-cost)

## References


