# Distance flown by charging zone {#sec-distance-flown-by-charging-zone}

This value presents the number of kilometers flown by charging zone.

```{r}
#| label: tbl-distance-per-charging-zone
#| tbl-cap: Distance flown per charging zone in million km

library(readxl)
library(dplyr)
library(gt)


read_xlsx("data/distance_by_charging_zone.xlsx") %>% 
  gt() %>% 
  cols_label(
    zone = "Charging zone",
    y2014 = "2014",
    y2015 = "2015",
    y2016 = "2016",
    y2017 = "2017",
    y2018 = "2018",
    y2019 = "2019",
    y2020 = "2020",
    y2021 = "2021",
    y2022 = "2022"
  ) %>% 
  fmt_number(
    columns = c(y2014:y2022),
    decimals = 0
  ) %>% 
  tab_options(
    table.font.size = "smaller"
  ) %>% 
  tab_source_note(
    source = md("*Source:EUROCONTROL Central Route Charges Office – Draft Internal data for 2022 and [Report on the Operation of the Route Charges System in 2021](https://www.eurocontrol.int/publication/report-operation-route-charges-system-2021)*")
  )
```

Please note that data for Estonia and Ukraine is not available from the beginning because these countries integrated in April 2017 and November 2021 respectively.

For the most updated information, the [Aviation Intelligence En Route Dashboard](https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html) can be accessed.

## Description

The Report on the Operation of the Route Charges System is published by the CRCO 
on an annual basis and provides data on traffic volumes and ATM costs for the 
States for which the CRCO collects en route and terminal charges.

[@tbl-distance-per-charging-zone] sets out the number of millions of kilometers
recorded in the airspace of the Contracting States from 2014 to 2022 for the 
calculation of route charges (great circle distance after deduction of 20 km for
departing and arriving flights) as well as the average annual variation observed 
during the same period.

Information on the various different charges levied by the CRCO, in particular 
the charge calculation methods, the basic billing documents, the methods of
payment and the submission of claims is described in [Customer Guide to Charges](https://www.eurocontrol.int/publication/customer-guide-route-charges).

## Related inputs

* @sec-if-average-flight-distance-and-flight-duration [IFR average flight distance and flight duration](#sec-if-average-flight-distance-and-flight-duration)

* @sec-en-route-ans-costs [En-route ANS costs](#sec-en-route-ans-costs)

* @sec-route-charge-share-per-market-segment [Route charge share per market segment](#sec-route-charge-share-per-market-segment)


