# En-route ANS costs {#sec-en-route-ans-costs}

## EUROCONTROL recommended values

The costs of Air Navigation Services (ANS) in en-route airspace that is under 
the control of States/ANSPs.

@tbl-ans-costs shows the real en-route ANS cost per and the Total en-route 
Service Units (TSU) for the EUROCONTROL Area in total and split into the SES 
States and the Other 10 States. The monetary values are presented in 2020 prices.

```{r}
#| label: tbl-ans-costs
#| tbl-cap: En-route ANS costs in million euros

library(readxl)
library(dplyr)
library(gt)

read_xlsx("data/er_ans_costs.xlsx") %>% 
  gt() %>% 
  cols_label(
    type = " ",
    y2015 = "2015",
    y2016 = "2016",
    y2017 = "2017",
    y2018 = "2018",
    y2019 = "2019",
    y2020 = "2020"
  ) %>% 
  fmt_currency(
    currency = "EUR",
    columns = y2015:y2020,
    rows = 1:3,
    decimals = 0
  ) %>%  fmt_currency(
    currency = "EUR",
    columns = y2015:y2020,
    rows = 7:9,
    decimals = 2
  ) %>% 
  tab_style(
    style = list(
      cell_text(
        weight = "bold")
      ),
      locations = cells_body(
        columns = type:y2020,
        rows = 3
      )
      ) %>% 
    tab_style(
    style = list(
      cell_text(
        weight = "bold")
      ),
      locations = cells_body(
        columns = type:y2020,
        rows = 6
      )
      ) %>% 
    tab_style(
    style = list(
      cell_text(
        weight = "bold")
      ),
      locations = cells_body(
        columns = type:y2020,
        rows = 9
      )
      ) %>% 
  tab_style(
    style = list(
      cell_fill(
        color = "#F5F7F9")
    ),
    locations = cells_body(
      columns = type:y2020,
      rows = 3
    )
  ) %>% 
  tab_style(
    style = list(
      cell_fill(
        color = "#F5F7F9")
    ),
    locations = cells_body(
      columns = type:y2020,
      rows = 6
    )
  ) %>% 
  tab_style(
    style = list(
      cell_fill(
        color = "#F5F7F9")
    ),
    locations = cells_body(
      columns = type:y2020,
      rows = 9
    )
  ) %>% 
  tab_options(
    table.width = pct(100)
   ) %>% 
   cols_width(
    type ~ pct(30),
    y2015:y2020 ~ pct(12)
  ) %>% 
  tab_options(
    column_labels.font.weight = "bold"
  ) %>% 
  tab_footnote(
    footnote = "SES States refer  to  the  27  Member  States  of  the European  Union  (EU),  plus  Switzerland and Norway",
    locations = cells_body(
      columns = type,
      rows = 1
    )
  ) %>% 
 tab_footnote(
    footnote = "Non‐SES States refer to ten States which are not bound by SES regulations but which were part of the EUROCONTROL Multilateral Route Charges System in 2020 (i.e. Albania, Armenia, Bosnia‐Herzegovina, Georgia, Moldova, North Macedonia, Serbia, Montenegro, United Kingdom and Türkiye)",
    locations = cells_body(
      columns = type,
      rows = 2
    )
  ) %>% 
  tab_source_note(
    source_note = md("*Source: [EUROCONTROL (2022), Performance Review Report (PRR) 2021. Figure 6.2](https://www.eurocontrol.int/publication/performance-review-report-prr-2021)*")
  )
```

## Description

The **En-route ANS costs per TSU**  in @tbl-ans-costs are calculated as the ratio 
between the **Total en-route ANS costs** and **Total en-route service units**.

:::{.callout-note}
Please note the difference between [Total Service Units (TSU)](https://ansperformance.eu/acronym/su/) and [Terminal Service Units (TNSU)](https://ansperformance.eu/acronym/tnsu/).
:::

:::{.callout-note}
The Unit Rate of Charge is the charge in euro applied by a Charging Zone to a 
flight operated by an aircraft of 50 metric tonnes (weight factor of 1.00) and 
flying 100 kilometres (distance factor of 1.00) in the charge area of that State.  
:::

The **Total en-route ANS costs** values in @tbl-ans-costs are actual values. 
Often these can also be presented as ‘determined’ (a projection in the future) 
costs. This is typically the case when en-route ANS costs are forecasted for 
a reference period of five years are costs pre determined by the SES States as
referred to in [Article 15(2)(a) of Regulation (EC) No 550/2004](http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CONSLEG:2004R0550:20091204:EN:PDF) 
for providing air navigation services.

The **Total en-route Service Units**, which are used for the calculation of route 
charges that airspace users are billed for the costs of air navigation services 
received. En-route service units of a specific flight are equal to the product of
the Distance Factor (the distance flown expressed in 100 kilometres) by the 
Aircraft Weight Factor square root of the Maximum Take Off Weight of the aircraft
which performed the flight (expressed in 50 tonnes).

:::{.callout-note}
Further information on calculating unit rates can be found on [customer guide to charges website](https://www.eurocontrol.int/publication/customer-guide-route-charges)
:::


## Other sources

Other source could be the EUROCONTROL Central Route Charges Office. At the time 
of writing, the most recent published version is the [2021 Report on the Operation of the
Route Charges System](https://www.eurocontrol.int/publication/report-operation-route-charges-system-2021).
Please, check regularly the [CRCO full list of reports on the operation of the route charges system](https://www.eurocontrol.int/library/search?f%5B0%5D=activity%3A768&f%5B1%5D=topic%3A1159&f%5B2%5D=activity%3A768&f%5B3%5D=topic%3A1159) 
for the latest information.

The CRCO calculates route charges using flight messages sent by the Contracting 
States’ Route Charges Offices (CRCOs) and additional flight information made
available via the EUROCONTROL Network Management Directorate (NMD). The CRCO 
bills aircraft operators on a monthly basis, collects charges and disburses the 
amounts collected to the States every week. 

## Comment

Terminal ANS costs and ANSP gate to gate economic performance are described 
separately in chapter 6 of the EUROCONTROL Performance Review Report[@ectrlprr2022].

## Related inputs

@sec-distance-flown-by-charging-zone [Distance flown by charging zone](#sec-distance-flown-by-charging-zone)

## References
