
# Foreword {-}

Although we cannot foresee when, or even if, the world will return to what it was
prior to the COVID- 19 pandemic, we have decided to publish this new edition of
the standard inputs as a valuable source of inputs for economic and 
cost-benefit analyses in aviation.
The recommended values are often based on 2019 statistics and data which do not
yet take account of the impact of the pandemic.

For this edition, the focus is on environmental values, a new value for airports,
turn-around time, and the introduction of two values related to drones.
Drones represent a highly complex and fast-moving market, which makes forecasting
more difficult than legacy aviation sectors.
Suggestions for improvement and collaboration are welcome.
Please send them to aviation.intelligence@eurocontrol.int.

We would like to make a special mention of the launch of the EUROCONTROL
Aviation Intelligence Portal, which provides valuable and up-to-date information
for economic analyses (https://ansperformance.eu/).
The Portal will soon include the standard inputs (2021) and more information 
of use for cost-benefit analyses.
