`r if (knitr:::is_html_output()) `
# Welcome {-}

This is the website for __"{{< meta title  >}}"__.

The EUROCONTROL Business Cases team regularly refreshes the content and the underlying data
in order to provide up-to-date information for interested readers.

# About us

The EUROCONTROL Business Cases team is a dedicated team of experts that support stakeholders who need to choose between different solutions and alternatives, using the best available data. For 20 years, EUROCONTROL has been providing ATM decision makers with a wide range of regularly updated Standard Inputs to help them to take rational long-term investment decision.

# Notice and Disclaimer {-}

The EUROCONTROL Business Cases team has made every effort to ensure that the information and analysis contained in this document are as accurate as possible. Only information from quoted sources has been used
and information relating to named parties has been checked with the parties concerned. Despite these
precautions, should you find any errors or inconsistencies we would be grateful if you could please bring them to
our attention. Our email address is [aviation.intelligence@eurocontrol.int](mailto:aviation.intelligence@eurocontrol.int)

This document is published by the EUROCONTROL Business Cases team in the interest of the exchange of
information.

Information contained in this document may not be modified without prior written permission from the
EUROCONTROL Business Cases team.

The views expressed herein do not necessarily respect the official views or policy of EUROCONTROL, which
makes no warranty, either implied or express, for the information contained in this document, neither does it
assume any legal liability or responsibility for the accuracy, completeness or usefulness of this information.




## Publications {-}

| EUROCONTROL Headquarters
| 96 Rue de la Fusée
| B-1130 BRUSSELS
| Tel: +32 (0)2 729 1152
| Fax: +32 (0)2 729 5149
| E-mail: publications@eurocontrol.int