# Introduction {.unnumbered}

This document provides a set of data commonly used in economic and financial analyses and appraisals, particulary in the field of ATM.

The aim of this document is to standardise the data used in the different ATM-related assessments, facilitate the data access for the different stakeholders involved and contribute to the comparability of different analyses through relying on the same data.

In this edition ({{< meta release-version >}}):

- The monetary values have been adjusted for inflation

- Several values have been updated to reflect the latest data available:
    -   @sec-transit-time [Transit time](#sec-transit-time)
    -   @sec-rate-of-fuel-burn [Rate of fuel burn](#sec-rate of-fuel-burn)
    -   @sec-if-average-flight-distance-and-flight-duration [IFR average flight distance and flight duration](sec-if-average-flight-distance-and-flight-duration)
    -   @sec-cost-of-aviation-fuel [Cost of aviation fuel](#sec-cost-of-aviation-fuel)
    -   @sec-value-of-an-average-passenger-flight [Value of an average passenger flight](#sec-value-of-an-average-passenger-flight)
    -   @sec-fleet-age [Fleet age](#sec-fleet-age)
    -   @sec-ansp-employment-cost [ANSP employment cost](#sec-ansp-employment-cost)
    -   @sec-asset-life [Asset life](#sec-asset-life)
    -   @sec-atm-cost-effectiveness-indicators [ATM cost effectiveness indicators](#sec-atm-cost-effectiveness-indicators)
    -   @sec-atm-operational-units [ATM operational units](#sec-atm-operational-units)
    -   @sec-passenger-value-of-time [Passenger value of time](#sec-passenger-value-of-time)
    -   @sec-value-of-statistical-injury [Value of a statistical injury](sec-value-of-statistical-injury)
    -   @sec-value-of-a-statistical-life [Value of a statistical life](sec-value-of-statistical-life)

Please note that the standard inputs have been compiled from EUROCONTROL data and intelligence, from values provided by airspace users, ANSPs, airports, IATA, EASA and other organisations, and from other relevant documents which are publicly available.

They are average values and may not be appropriate in all circumstances. The document also gives details of the sources of information, and discusses the applicability and use of the values.

This document will remain a living document, and so comments and suggestions are very welcome. Readers are invited to send these to [{{< var email.aiu >}}](mailto:{{< var email.aiu >}}).

## Details per data item {.unlisted .unnumbered}

For each standard input, the following information is provided, where relevant.

| Section                        | Description                                                                                                                                                                 |
|:-----------------------|:-----------------------------------------------|
| EUROCONTROL recommended values | One or a set of recommended values put forward by EUROCONTROL for the specific indicator.                                                                                   |
| Description                    | Any relevant information or details regarding the recommended value (e.g. information on how the value was computed, the limitations on using the value, or other remarks). |
| When to use the input?         | A recommendation on when and where the specific input can be beneficial is provided here.                                                                                   |
| Comments                       | Any questions or further comments regarding the source or derivation of the value, for example the degree of confidence in the values and sources cited.                    |
| Related inputs                 | A link to other related standard inputs included in the document.                                                                                                           |
| References                     | A list of sources used for the specific input.                                                                                                                              |
