# Operational Cancellation Rate {#operational-cancellation-rate}

## Definition

IFR flight cancellation rate in Europe.

## EUROCONTROL recommended sources

Value
:   
```{r, operational-cancellation-rate}
library(tibble)
library(gt)
library(tidyr)

tribble(
  ~ year, ~ pct,
  2013, 0.015,
  2014, 0.016,
  2015, 0.015,
  2016, 0.016,
  2017, 0.015,
  2018, 0.020,
  2019, 0.017
) %>% 
  pivot_wider(names_from = year, values_from = pct) %>% 
  gt() %>% 
  tab_header(title = "Operational cancellation rate") %>% 
  fmt_percent(columns = 1:7, decimals = 1) %>% 
  opt_align_table_header(align = "left")
```

Source
:   EUROCONTROL (2019) – Based on operational cancellation data supplied by 30 European coordinated airports reporting to CODA under EC Regulation No 390/2013.  
    https://www.eurocontrol.int/publication/all-causes-delay-and-cancellations-air-transport-europe-2019  
    Reports from previous years are available in the EUROCONTROL library:  
    https://www.eurocontrol.int/library.


## Description

According to Annex IV of Commission Implementing Regulation (EU No 390/2013), an ‘operational cancellation’ means an arrival or departure of a scheduled flight to which the following conditions apply:

* the flight received an airport slot; and
* the flight was confirmed by the air carrier the day before operations and/or it featured in the daily
list of flight schedules produced by the airport operator the day before of operations; but
* the actual landing or take-off did not occur.

For 2019, airlines providing operational cancellation data to CODA reported operational cancellations of 1.7% (this includes daily peaks of up to 9.4% due to ATC industrial action or large-scale weather events).

Section 9 of the referenced document contains a detailed analysis of the cancellations.


## Related standard inputs

[Cancellation cost].

