# Rate of fuel burn

## Definition
Average number of kilogrammes per hour of fuel burnt by an aircraft in
different flight phases and with different load factors

## EUROCONTROL recommended sources

Value
:   Fuel burn rates (kg/minutes) in flight phases where delay can occur for
    most representative aircraft types flying (with restriction in use[^4])
    ```{r, fuel-burn-rates}
    # see gt example for custom table
    library(readr)
    library(gt)
    library(magrittr)
    
    read_csv("data/rate-of-fuel-burn.csv") %>% 
      gt() %>% 
      fmt_markdown(columns = TRUE)

    ```

Source
:   EUROCONTROL BADA (Base of Aircraft Data)
    https://www.eurocontrol.int/model/bada

[^4]: It is strictly prohibited to use the fuel burn values to compare fuel
efficiency and emission data between aircraft types from the same or different
manufactures.
Data are provided here to allow the drafting of aggregate business cases.

[^5]: The useful load is the sum of the payload and the fuel.
The maximum useful load is approximately the MTOW minus the empty aircraft
weight. The "% of max useful load" referred to in the recommended value
indicates how the aircraft is loaded, in terms of payload and fuel (combined).
This must also not be confused with the load factor, which indicates how
the aircraft is loaded in terms of payload only (i.e. not taking the fuel into
account).


## Description
The above data originate from the Base of Aircraft Data (BADA), which is an
aircraft performance model (APM) developed and maintained by EUROCONTROL,
with the active cooperation of aircraft manufacturers and operating airlines.
The data extracted make use of three different families of the BADA model
(BADA 3, BADA 4 and BADA Helicopters).

The data are to be treated as approximations, which give an indication of
the average fuel burn per flight phase.
These data do not, however, take weather and atmospheric influences into
account, nor the impact of specific flight conditions (speed, altitude, etc.),
and they are therefore to be used with a correction factor when applied in
a specific context.

Organisations which are interested in more aircraft types can request access
to the full BADA model (see link above).


## Related standard inputs

[Amount of emissions released by fuel burn], [cost of emissions] and
[IFR flight information per market segment](#ifr-flight-information-per-market-segment).


## Other possible sources

Source 1
:   ICAO (2018) – ICAO Carbon Emissions Calculator Methodology, Version 11,
    June 2018
    https://www.icao.int/environmental-protection/CarbonOffset/Documents/Methodology%20ICAO%20Carbon%20Calc ulator_v11-2018.pdf

Description 1
:   ICAO has developed a methodology to calculate the carbon dioxide emissions
    from air travel for use in offset programmes.
    The ICAO Carbon Emissions Calculator allows passengers to estimate the
    emissions attributed to their air travel.
    One of the inputs is the fuel burn for 312 equivalent aircraft types,
    Appendix C: ICAO Fuel Consumption Table, page 17.

Source 2
:   EUROCONTROL Advanced Emission Model (AEM)
    https://www.eurocontrol.int/model/advanced-emission-model

Description 2
:   The advanced emission model (AEM) is a standalone application, developed
    and maintained by the EUROCONTROL Experimental Centre, which estimates
    aircraft emissions and fuel burn.
    The AEM can estimate:
    
  * the mass of fuel burned by the main engines of a specified type of
    aircraft with a specified type of engine flying a specified 4D trajectory;
  * the corresponding masses of certain gaseous and particulate emissions
    which are produced by the burning of that fuel.
    Access to the tool requires an AEM user license.

Source 3
:   ICAO Engine Emissions Databank
    https://easa.europa.eu/document-library/icao-aircraft-engine-emissions-databank

Description 3
:   Rates of fuel burn for different phases of flight for individual
    engine types may be found in the manufacturers’ datasheets in the
    ICAO Engine Emissions Databank.
