# Value of a statistical injury {#sec-value-of-statistical-injury}

The value of a statistical injury represents the **monetary value of an improvement in safety to achieve a risk reduction which would prevent one statistical injury.** 
It can be used as a proxy to monetise the impact of an injury resulting from 
transport accidents.

@tbl-value-of-injury shows the estimation of the value of an injury as a fraction of
the [value of statistical life](#sec-value-of-a-statistical-life), following the approach and numbers presented in 
the Handbook on the external costs of transport.[@ecdgmove2019] This approach assumes six
levels of injury, where Maximum Abbreviated Injury Scale (MAIS) 1 and MAIS 2 represent slight injury, MAIS 3 through MAIS 5 represent serious injury and MAIS 6 represents fatality.

Thus, in @tbl-value-of-injury are presented the levels of injury, the share that the value 
of injury represents from the value of life and the calculated cost of injury in
euros, based on these percentages and the estimated value of statistical life as 
presented in [@sec-value-of-a-statistical-life].

```{r}
#| label: tbl-value-of-injury
#| tbl-cap: Estimated value of statistical injury

library(readxl)
library(dplyr)
library(gt)

read_xlsx("data/value_statistical_injury.xlsx",
          range = "A1:C7") %>% 
  gt() %>% 
  cols_label(
    category = "Injury category",
    share = "Share of VSL",
    absolute = "Value of injury"
  ) %>% 
  fmt_currency(
    columns = "absolute",
    currency = "EUR",
    decimals = 0
  ) %>% 
  fmt_percent(
    columns = "share",
    decimals = 0
  ) %>% 
  cols_align(
    align = "center",
    columns = share
  ) %>% 
  tab_source_note(
    source = md("*[Source: European Commission DG MOVE (2019), Handbook on the external costs of transport](https://op.europa.eu/en/publication-detail/-/publication/9781f65f-8448-11ea-bf12-01aa75ed71a1)*")
  ) %>% 
  tab_options(
    table.width = pct(100)
   ) %>% 
   cols_width(
    everything() ~ pct(33),
  ) %>% 
  tab_options(
    column_labels.font.weight = "bold"
  )
```

## Comments

The above data should be treated with caution as there may be legal implications.

## Other possible sources

Below are presented some sources recommended to be consulted in the frame of this input:

*European Commission DG REGIO, Guide to Cost-Benefit Analysis of Investment Projects for Cohesion Policy 2014-2020*[@ecdgregio2014]

## Related inputs

@sec-accident-incident-statistics [Accident/incident statistics](#sec-accident-incident-statistics)

@sec-value-of-a-statistical-life [Value of a statistical life](#sec-value-of-a-statistical-life)

## References
