# Accident/incident statistics {#sec-accident-incident-statistics}

## EUROCONTROL recommended sources

According to **[ICAO Annex 13](https://www.icao.int/safety/airnavigation/aig/pages/documents.aspx):**

An **accident** is an occurrence associated with the operation of an aircraft …, 
in which (a) a person is fatally or seriously injured… or (b) the aircraft sustains
damage or structural failure …or (c) the aircraft is missing or completely inaccessible.^[Full definition of accident: An occurrence associated with the operation of an aircraft which takes place between the time any person boards the aircraft with the intention of flight until such time as all such persons have disembarked, in which (a) a person is fatally or seriously injured as a result of being in the aircraft; or direct contact with any part of the aircraft, including parts which have become detached from the aircraft; or direct exposure to jet blast (except when the injuries are from natural causes, self-inflicted or inflicted by other persons, or when the injuries are to stowaways hiding outside the areas normally available to the passengers or crew); or (b) the aircraft sustains damage or structural failure which: adversely affects the structural strength, performance or flight characteristics of the aircraft and would normally require major repair or replacement of the affected component (except for engine failure or damage, when the damage is limited to the engine, its cowlings or accessories; or for damage limited to propellers, wing tips, antennas, tires, brakes, fairings, small dents or puncture holes in the aircraft skin); or (c) the aircraft is missing or is completely inaccessible. (ICAO Annex 13)]

An **incident** is an occurrence, other than an accident, associated with the 
operation of an aircraft which affects or could affect the safety of operations.

The following documents are key sources of the latest statistics on accidents 
and incidents occurring in the aviation domain, as well as the related fatalities 
and injuries.

* *EASA Annual Safety Review[@AnnualSafetyReview]*

    Provides both, a statistical summary of aviation safety in the EASA Member 
    States and identifies the most important safety challenges faced by European
    aviation today. The key statistics on accidents and serious incidents in the 
    different aviation domains can be found at the start of each chapter in the 
    Annual Safety Review.

* *EUROCONTROL voluntary ATM incident reporting (EVAIR) safety bulletin[@atmincidentreport]*
    
    Collects low-severity ATM incidents which involve pilots and controllers. 
    The established process and kinds of data provided by airlines and ANSP Safety 
    Management Systems (SMS) allow day to day analysis and, in this regard, 
    identification of the causes of incidents. The data are collected from the
    entire ECAC region and from neighbouring airspace, such as the Eastern part 
    of the ICAO EUR region, the Middle East, Africa, etc.

* *IATA Annual Safety Report[@iata:safety:report]*

    Provides the industry with critical information derived from the analysis 
    of aviation accidents to enable to understand safety risks in the industry 
    and to propose mitigation strategies.

## Further reading

The sources listed hereafter are those recommended to consult for further information:

* *EU Regulation (EU) No 996/2010 on the investigation and prevention of accidents and incidents in civil aviation and repealing Directive 94/56/EC[@eureg9962010]*
    contains a definition of accidents and incidents

* *EU Regulation (EU) No 376/2014 on the reporting, analysis and follow-up of occurrences in civil aviation, amending Regulation (EU) No 996/2010 of the European Parliament and of the Council and repealing Directive 2003/42/EC of the European Parliament and of the Council and Commission Regulations (EC) No 1321/2007 and (EC) No 1330/2007[@eureg3762014]*
    contains information on the regulatory requirements reporting, analysis and 
    follow-up of occurrences, which include accidents and incidents in civil aviation

* *EU Single Sky Performance Review Body, Annual Monitoring Report[@EUSingleSky]*
    The Annual Monitoring Reports are prepared by the Performance Review Body (PRB) of the Single European Sky (SES)

* *ICAO safety reports[@icao:safety]*
    provides overview of worldwide aviation safety performance and collaborative
    efforts by international air transport stakeholders to further improve safety
    in light of the sustained growth of the sector
    
* *Performance Review Commission (2023) Draft Performance Review Report (PRR) 2023[@ectrlprr2023]*
    Annual Performance Review Reports issued by the Performance Review Commission
    provide an annual review of Europe’s ATM safety performance

* *SKYbrary* [@SkyBrary]
    is an electronic repository of safety knowledge related to ATM and aviation 
    safety in general. It contains information about accidents and serious 
    incidents by aircraft type and is also a portal which gives users access 
    to the safety data made available on the websites of various aviation 
    organisations (regulators, service providers, industry).

## When to use the input?

This input is recommended to be used in the instances where safety is an 
important factor, namely in terms of accident reduction.

## References
