# Asset life {#sec-asset-life}

## EUROCONTROL recommended values

@tbl-asset-life presents the accounting period, in years, for a given asset used 
to derive the depreciation of investment expenditure.

```{r}
#| label: tbl-asset-life
#| tbl-cap: Estimated asset life

library(readxl)
library(dplyr)
library(gt)


read_xlsx(here::here("data", "asset_life.xlsx")) %>% 
  gt() %>% 
  cols_label(
    asset = "Asset type",
    min = "Expected life (years)",
    max = "Maximum expected life"
  ) %>% 
  cols_align(
    align = "center",
    columns = min:max
  ) %>% 
  cols_merge_range(min,max, sep = "--", autohide = TRUE) %>% 
   tab_options(
    table.width = pct(100)
   ) %>% 
   cols_width(
    everything() ~ pct(50)
  ) %>% 
  tab_options(
    column_labels.font.weight = "bold"
  ) %>% 
  tab_source_note(
    source = md("*Source: EUROCONTROL (2011), Principles for Establishing the Cost-Base for Route Charges and the Calculation of the Unit Rates*")
  )
```

Asset life as used in cost-benefit analyses reflects the expected operating 
life of the specific equipment concerned, which is also the basis for calculating
depreciation costs which are taken into account to determine route charges.

The above data provide indicative parameters for classes of equipment for economic
analyses. The actual percentages to be applied in calculating the depreciation 
of fixed assets must be determined in accordance with the expected operating 
life and the pertinent [International Financial Reporting Standards](https://www.ifrs.org/) 
issued by the [International Accounting Standards Board](https://www.ifrs.org/groups/international-accounting-standards-board/).

## Other possible sources

* *ICAO (2013), Manual on Air Navigation Services Economics (Doc 9161)*[@icao2013]

* *European Commission DG REGIO (2014), Guide to Cost-Benefit Analysis of Investment Projects for Cohesion Policy 2014-2020*[@ecdgregio2014]

* *European Commission DG REGIO (2022), Economic appraisal vademecum 2021-2027 General principles and sector applications*[@ecdgregiovademecum2022]

## Refrences
