# ATM cost-effectiveness indicators {#sec-atm-cost-effectiveness-indicators}

## EUROCONTROL recommended values

This section considers some key performance indicators of cost-effectiveness and 
productivity for the Air Navigation Services Providers (ANSP) in the EUROCONTROL area.

```{r}
#| label: tbl-atm-cost-effectiveness
#| tbl-cap: Average ANSP cost-effectiveness and productivity indicators

library(readxl)
library(dplyr)
library(gt)

read_xlsx(here::here("data", "atm_cost_effectiveness.xlsx")) %>% 
  gt() %>% 
  cols_label(
    year = "Year",
    productivity = "ATCO-hour productivity",
    empl_cost = "Employment cost per ATCO hour",
    ratio = "Support staff ratio"
  ) %>% 
cols_align(
  align = "right",
  columns = productivity:ratio
) %>% 
  cols_align(
  align = "left",
  columns = year
) %>% 
  fmt_currency(
    currency = "EUR",
    columns = empl_cost,
    decimals = 0
  ) %>% 
  fmt_number(
    columns = ratio,
    decimals = 2
  ) %>% 
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "year"
    )
  ) %>% 
  tab_options(
    table.width = pct(100)
   ) %>% 
   cols_width(
    year ~ px(40),
    productivity ~ px(120),
    empl_cost ~ px(120),
    ratio ~ px(120)
  ) %>% 
  tab_options(
    column_labels.font.weight = "bold"
  ) %>% 
  tab_options(
    column_labels.font.weight = "bold"
  ) %>% 
   tab_footnote(
    footnote = "Unit: composite flight-hours per ATCO-hour",
    locations = cells_column_labels(
      column = productivity
    )
  ) %>% 
  tab_footnote(
    footnote = "Unit: euro per ATCO-hour in OPS",
    locations = cells_column_labels(
      column = empl_cost
    )
  ) %>% 
  tab_footnote(
    footnote = "Unit: gate-to-gate ANS staff to ATCOs in OPS",
    locations = cells_column_labels(
      column = ratio
    )
  ) %>% 
tab_source_note(
  source_note = md("*Source: [EUROCONTROL PRU, ATM Cost-Effectiveness (ACE) Benchmarking Reports](https://ansperformance.eu/publications/prc/ace/)*")
)
```

@tbl-atm-cost-effectiveness shows the **average** values for the European system for the 
years 2015 through 2024. On top of these values, 2024 key performance drivers of financial
cost-effectiveness for ANSPs are summarised in Figure 3.14 of ACE Benchmarking Report 2026 Edition. [@ATMCostEffectiveness]

Furthermore, **a wide variation per ANSP can be observed** in ACE Benchmarking 
Report 2026 Edition. [@ATMCostEffectiveness]

* ATCO productivity ranges from 0.22 to 2.23 (Figure 3.18)

* ATCO in OPS employment costs vary from a minimum of €32 to a maximum of €375 per ATCO-hour (Figure 3.22)

* Support cost ratio varies from 0.36 to 1.33 in 2024 (Annex 3, Table 0.1)

The ACE benchmarking reports [@ATMCostEffectiveness] comprise data about and 
analysis of cost-effectiveness and productivity for the ANSPs in EUROCONTROL’s
Member States. The key performance drivers of cost-effectiveness are (i) productivity,
(ii) employment costs and (iii) support costs, comprising costs for non-ATCOs 
in OPS employment, non-staff operating costs, exceptional costs, depreciation,
and capital-related costs

:::{.callout-note}
The employment costs above refer to gate-to-gate cost (i.e. en-route and terminal 
costs) and are expressed in nominal prices.
:::

## Related inputs

@sec-ansp-employment-cost [ANSP employment cost](#sec-ansp-employment-cost)

## References


