# Version changes {#sec-change-log .unnumbered}

Below is presented a list of values that have been updated in 
this release of the document. Its aim is to explain to 
the user in which cases a divergence between the values with previous versions is due to an update. 

To consult the previous versions of the document, please refer to the option 
"Previous Versions" at the top of the page.

* [General parameters](#sec-conversions)

* [Geographical areas](#sec-geographical-areas)

* [Air traffic statistics and forecasts](#sec-air-traffic-statistics-and-forecasts)

* [Air traffic delay](#sec-air-traffic-delay)

* [Cost of emissions](#sec-cost-of-emissions)

* [Cost of noise](#sec-cost-of-noise)

* [Average number of passengers](#sec-average-number-of-passengers)

* [Cost of diversion](#sec-cost-of-diversion)

* [Load factor - cargo](#sec-load-factor-cargo)

* [Load factor - passengers](#sec-load-factor-passengers)

* [Value of an average passenger flight](#sec-value-of-an-average-passenger-flight)

* [Passenger value of time](#sec-passenger-value-of-time)

* [Value of a statistical life](#sec-value-of-a-statistical-life)


```{r}
##| label: tbl-change-log
##| tbl-cap: Version change register

#library(readxl)
#library(dplyr, quietly = TRUE)
#library(gt)
#library(here)

#read_xlsx(here("data", "change_log.xlsx")) %>% 
 # gt() %>%
  #cols_label(
   # input = "Input",
    #release_10.0.3 = "Release 10.0.3",
  #  release_10 = "Release 10"
  #) %>% 
  #cols_align(
  #  align = "left",
  #  columns = c(1:3)
  #) %>%
  #tab_options(
  #  table.width = pct(100),
  #) %>%
  #cols_width(
  #  input ~ pct(40),
  #  release_10.0.3 ~ pct(30),
  #  release_10 ~ pct (30)
  #) %>% 
  #tab_options(
  #  column_labels.font.weight = "bold"
  #) %>%
  #tab_row_group(
  #  label = "FINANCIAL VALUES",
  #  rows = 46:47
  #) %>%
  #tab_row_group(
  #  label = "SAFETY",
  #  rows = 43:45  
  #) %>%
  #tab_row_group(
  #  label = "PASSENGERS",
  #  rows = 41:42
  #) %>%
  #tab_row_group(
  #  label = "DRONES",
  #  rows = 39:40
  #) %>%
  #tab_row_group(
  #  label = "AIRPORTS",
  #  rows = 37:38
  #) %>%
  #tab_row_group(
  #  label = "AIR TRAFFIC MANAGEMENT",
  #  rows = 29:36
  #) %>%
  #tab_row_group(
  #  label = "AIRSPACE USERS",
  #  rows = 12:28
  #) %>%
  #tab_row_group(
  #  label = "ENVIRONMENT",
  #  rows = 6:11
  #) %>%
  #tab_row_group(
  #  label = "TRAFFIC AND CAPACITY",
  #  rows = 1:5
  #) %>%
  #tab_options(
  #  row_group.background.color = "#F5F7F9",
  #  row_group.font.weight = "bold"
  #)
```

