# Cost of aviation fuel {#sec-cost-of-aviation-fuel}

## EUROCONTROL recommended sources

The source recommended to consult for the latest data on the cost of aviation 
fuel is [IATA Jet Fuel Price Monitor](https://eurocontrol.sharepoint.com/sites/ECTL-Business_Cases/Shared Documents/Standard_Inputs/1. NEW_2022/Values/Cost of aviation fuel/IATA Jet Fuel Price Monitor).

On its website, IATA provides jet fuel prices for the major regions of the world,
together with analysis and commentary. The values are based on [Platts Energy Market Data](http://www.platts.com/).

When estimating the jet fuel price, consideration should be given to the selection of the geographical area, and hence currency, as a change in oil price can have a different effect on the jet fuel price owing to currency fluctuations, e.g. the downturn in the euro in 2015.

The ‘spread’ between the aviation fuel price and the underlying oil price covers the cost of refining, but it can vary significantly with time depending on underlying demand (e.g. from consumers needing a similar fraction to aviation), and on supply problems (such as a breakdown at a refinery or increasing local prices relative to oil).

## Other possible sources

Other sources that may be interesting to consult to estimate the price of jet fuel include:

* *IATA Airline Industry Economic Performance Report and Tables*[@iataeconperf]

* *US Energy Information Administration (2022), Annual Energy Outlook 2023*[@eia2023]

## References