# Fleet age {#sec-fleet-age}

##	EUROCONTROL recommended values

The sections below refer to the age of the aircraft operating IFR flights in Europe.

### Age, number of aircraft and number of flights according to the aircraft build year

```{r}
#| label: tbl-fleet-age 
#| tbl-cap: Build year of civil aircraft operating in EUROCONTROL Network Manager area in 2022

library(readxl)
library(dplyr)
library(gt)

read_xlsx(here::here("data", "fleet_age_build_year.xlsx")) %>% 
  gt() %>% 
  cols_label(
    year ="Build Year",
    age ="Age",
    number ="Number of aircraft",
    flights ="Flights in 2022"
  ) %>% 
  fmt_number(
    columns = c(number, flights),
    use_seps = TRUE,
    decimals = 0
  ) %>% 
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = year:flights,
      rows = 44
    )
  ) %>% 
  cols_align(
  align = "right",
  columns = age:flights
) %>% 
   tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "year"
    )
  ) %>% 
  tab_options(
    table.width = pct(100)
   ) %>% 
   cols_width(
    everything() ~ pct(25)
  ) %>% 
  tab_options(
    column_labels.font.weight = "bold"
  ) %>%  
  tab_footnote(
    footnote = "This value may vary from the total number of flights reported earlier in this document due to a slight difference in scope of data available",
    locations = cells_body(
      columns = flights,
      rows = 44
    )
    ) %>% 
  tab_source_note (
    source = md("*Source: EUROCONTROL Network Manager flight plans and PRISME fleet data, March 2023*")
  )
```

The information presented in @tbl-fleet-age is derived from flight plans submitted to 
the EUROCONTROL Network Manager for flights in 2022. These aircraft were therefore
active in European airspace at some point during that year. The information was
analysed using the EUROCONTROL PRISME fleet database to derive the aircraft ages.

Since the numbers are based on flight plans, they exclude aircraft which do not
fly in controlled airspace and therefore do not submit flight plans to the NM. 
The 301 aircraft whose age was unknown were aircraft which are not recorded in 
the PRISME database. These are mostly privately owned aircraft or aircraft based 
outside Europe, together with some smaller aircraft not flying regularly in 
controlled airspace and some new aircraft which do not feature in the database.


### Average aircraft age per flight (EU27+EFTA) 

@fig-average-aircraft-age shows the average aircraft age in years by EUROCONTROL 
market segment[@ectl:market:seg:2022] for the aircraft operating in 2022.
 
![Average aircraft age per flight in EU27 + EFTA^[European Free Trade Association whose Member States comprise Iceland, Liechtenstein, Norway, and Switzerland] [@ectrl:statfor:sid]](../figures/aircraft_age.svg){#fig-average-aircraft-age}

:::{.callout-note}
EUROCONTROL market segments were updated in 2022 and saw the “Traditional 
Scheduled” segment split into “Mainline” and “Regional” according to EUROCONTROL
Market Segment Rules.[@ectl:market:seg:2022] The new segmentation started to be 
taken into account as of 2019, which explains some segments being set at zero 
before or after that date.
:::

Low-cost carriers have the youngest fleet on average, at 9 years in 2022, while 
charter and all-cargo have older fleets, at 15 and 22 years respectively. The 
increase in market share of all-cargo and business aviation in the aftermath of 
the COVID-19 pandemic, has pushed the average age of the overall fleet to 11.6 
years in 2022 from 11.1 in 2019.

### Commercial aircraft fleet by age of aircraft

@fig-com-aircraft-fleet shows the commercial aircraft fleet size by age of aircraft.

![Average aircraft age per flight  (EU27+EFTA+UK)[@eurostataircraftfleet]](../figures/aircraft_fleet_age.svg){#fig-com-aircraft-fleet}


EUROSTAT publishes annual statistics on commercial aircraft fleet by age of 
aircraft and country of operator/country of registration.

## When to use the inputs?

Depending on the market, an aircraft can remain in service for about 30 years.
While an aircraft follows a specific maintenance cycle, its performance can 
degrade over time due to engine and aerodynamic deterioration, leading to 
additional CO~2~ emissions. Fleet renewal helps reduce aviation’s environmental 
impact as newer aircraft tend to be more fuel efficient and quieter, therefore 
the average age of the European fleet is a good indicator of its environmental 
performance.

## Related inputs

@sec-number-of-ifr-flights [Number of IFR flights](#sec-number-of-ifr-flights)

@sec-fleet-size [Fleet size](#sec-fleet-size)

## References
