# Rate of fuel burn {#sec-rate-of-fuel-burn}

## EUROCONTROL recommended values

This section provides the average number of kilogrames per minute of fuel burn by operator segments in different flight phases.

```{r}
#| label: tbl-rate-fuel-burn
#| tbl-cap: Average fuel burn rates (kg/minute)

#Import aircraft performance data
library(dplyr)
library(gt)

# Create the table
read_xlsx(here("data","fuel_burn_rate.xlsx")) %>% 
  gt() %>% 
  # Change column tags
  cols_label(
    A = "Flight phase",
    B = "Taxi",
    C = "65%",
    D = "En route",
    E = "Arrival Management",
    G = "65%",
  ) %>%
  # Align columns
  cols_align(
    align = "left",
    columns = c(1)
  ) %>%
    cols_align(
    align = "right",
    columns = c(2:6)
  ) %>%
  # Colour rows
  tab_style(
    style = list(cell_text(indent = pct(10))),
    locations = cells_body(row=c(2:4), column=1)
  )%>%
  # Adding caption
  tab_caption(caption = md("Average fuel burn rates (kg/minute)")
  ) %>% 
  # Hiding columns
  cols_hide(columns = c(C, G)
  ) %>%
  tab_source_note(
    source_note = md("Based on EUROCONTROL [BADA](https://www.eurocontrol.int/model/bada) and [PRISME](https://ansperformance.eu/acronym/prisme/) data")
  ) %>%
# Columns width
  tab_options(
    table.width = pct(100),
  ) %>%
  cols_width(
    A ~ pct(100/4),
    B ~ pct(100/4),
    D ~ pct(100/4),
    E ~ pct(100/4),
  ) %>%
# Label row
  tab_options(
    column_labels.font.weight = "bold"
  ) 
```

## Description

@tbl-rate-fuel-burn originates from the Base of Aircraft Data (BADA), an Aircraft Performance Model (APM) developed and maintained by EUROCONTROL, with the active cooperation of aircraft manufacturers and operating airlines. The data extracted use three different families of the BADA model (BADA 3, BADA 4, and BADA Helicopters).

The operating segment values are weighted averages calculated based on (i) the number of flights per aircraft type (taxi and arrival phases) or (ii) the number of flight hours per aircraft type (en-route phase). The analysis covers the most-flying aircraft models in Europe, as per the flight plans submitted to the Network Manager (NM) in 2022 (EUROCONTROL PRISME):

-   **Scheduled aviation**: Grouping three (3) categories from the EUROCONTROL Market Segment Rules [@ectl:market:seg:2022]:

    -   **Regional (top 5):** AT76, E190, E195, CRJ9, and AT75.
    
    -   **Mainline + Low cost (top 15):** (a) narrow-body aircraft (B738, A320, A319, A20N, A321, A21N, B38M, BCS3, B734) and (b) wide-body aircraft (B77W, B789, A333, A332, B788, A359).

-   **Business aviation (top 5):** C56X, PC12, BE20, E55P, and GLEX.

-   **Rotorcraft (top 5):** S92, A139, EC75, AS32, and EC35.

The above selection of aircraft covers (i) 76% of the IFR flights and (ii) 79% of the IFR flight hours registered by the NM in 2022. 

## When to use the values?

The user should treat the @tbl-rate-fuel-burn values as high-level approximations of the average fuel burn per flight phase. Note that:

i)  regional and business aviation groupings encompass turbofan-powered and turboprop-powered aircraft with fuel burn rates significantly different between them;

ii) the performance data do not consider the weather and atmospheric influences; and

iii) the performance data do not consider the impact of specific flight conditions (speed, altitude, aircraft weight, etc.).

Organisations interested in more aircraft types can request access to the full BADA model.

## Other possible sources

Below, a list of other applicable sources that consider fuel burn rates:

-   *ICAO Carbon Emissions Calculator:* [@emissionscalc] ICAO has developed a methodology to calculate the carbon dioxide emissions from air travel for use in offset programmes. The methodology applies the best publicly available industry data to account for various factors such as aircraft types, route-specific data, passenger load factors and cargo carried.

-   *EUROCONTROL Advanced Emission Model (AEM):* [@ectrl:em:model] Standalone application, developed and maintained by the EUROCONTROL Innovation Hub, which estimates aircraft emissions and fuel burn. The AEM can estimate (i) the mass of fuel burned by the main engines of a specified type of aircraft with a specified type of engine flying a specified 4D trajectory; and (ii) the corresponding masses of certain gaseous and particulate emissions which are produced by the burning of that fuel. Access to the tool requires an AEM user license.

-   *ICAO Engine Emissions Databank:* [@icao:databank] Manufacturer's datasheets that may contain the rates of fuel burn for different flight phases and individual engine types.

## Related inputs

@sec-fleet-size [Fleet size](#sec-fleet-size)

## References
