# Route charge share per market segment {#sec-route-charge-share-per-market-segment}

## EUROCONTROL recommended values

This input presents the proportion of route charges^[There are different sorts of air navigation charges, namely route charges, terminal navigation charges and communication charges. The above distribution relates to route charges only.]
from ATM services in Europe (infrastructure, staff, and other operational costs) 
collected per market segment in 2022.[@ectl:market:seg:2022]

```{r}
library(readxl)
library(dplyr)
library(gt)

#| label: tbl-route-charge
#| tbl-cap: Proportion of route charges per market segment in 2022

read_xlsx(here::here("data", "route_charges_share.xlsx")) %>% 
  gt() %>% 
  cols_label(
    segment = "Market segment",
    share_flights = "As % of flights",
    share_nm = "As % of NM flown",
    share_charge = "As % of total charges collected"
  ) %>% 
  fmt_percent(
    columns = share_flights:share_charge,
    decimals = 1
  ) %>% 
  cols_align(
    align = "center",
    columns = share_flights:share_charge
  ) %>% 
  tab_options(
    table.width = pct(100)
   ) %>% 
   cols_width(
    share_flights:share_charge ~ pct(25),
  ) %>% 
  tab_options(
    column_labels.font.weight = "bold"
  ) %>% 
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = everything(),
      rows = 9
    )
  ) %>% 
  tab_source_note(
    source_note = md("*Source: Calculated based on data from EUROCONTROL STATFOR, EUROCONTROL PRISME and EUROCONTROL CRCO*")
  )
```

On behalf of EUROCONTROL Member States, CRCO bills and collects route charges, 
which fund air navigation facilities and services and support air traffic management
developments. It also bills and collects, on a bilateral basis, terminal charges,
and air navigation charges on behalf of non-Member States, as well as communication 
charges in the Shanwick area.

Each aircraft operator receives a single bill per month in euros, no matter how 
many EUROCONTROL Member States were overflown. The billing and recovery of air 
navigation charges ensure that air navigation facilities and services are steadily
financed and safely operated, paving the way for the future evolution of the
pan-European ATM system in the context of the Single European Sky and the 
European ATM Master Plan (SESAR).

Information on the different charges levied by the CRCO, in particular the charge
calculation methods, the basic billing documents, the methods of payment and the
submission of claims, can be found in the [customer guide to charges](https://www.eurocontrol.int/publication/customer-guide-route-charges).

## Related inputs

@sec-number-of-ifr-flights [Number of IFR flights](#sec-number-of-ifr-flights)

@sec-distance-flown-by-charging-zone [Distance flown by charging zone](#sec-distance-flown-by-charging-zone)

@sec-en-route-ans-costs [En-route ANS cost](#sec-en-route-ans-costs)

## References

