# Sustainable aviation fuels (SAF) blending

## Definition

The SAF blend is the share of Sustainable Aviation Fuels used for aviation fuels.

## EUROCONTROL recommended values

```{r}
#| label: tbl-inflation-table
#| tbl-cap: Shadow Cost of Carbon for EU27 in €2021 prices

library(readxl)
library(dplyr)
library(gt)

# read from CSV (exported directly from Eurostat, see R/export_inflation.R)
readxl::read_xlsx(here::here("data", "Shadow_Cost_of_Carbon_v10.xlsx"),
                  sheet = "Tidy_Data",
                  range = "A1:B31" 
                  ) %>%

  # format the table
  gt() %>%
  tab_source_note(
    source_note = md("Source: [European Investment Bank - The EIB Group Climate Bank Roadmap 2021-2025](https://www.eib.org/en/publications/the-eib-group-climate-bank-roadmap)")
  ) %>%
  cols_label(
    Year  = "Year",
    Cost = "Carbon cost",
   ) %>%
  fmt_number(
    columns = vars(Cost),
    decimals = 0
   ) %>% 
  tab_options(
    table.width = pct(50)
   ) %>% 
   cols_width(
    everything() ~ pct(50)
  ) %>% 
  tab_options(
    column_labels.font.weight = "bold"
  ) %>% 
  cols_align(
    align = "left",
    columns = Year
  ) %>% 
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "Year"
    )
  )
```

## Description

The table shows the forecast of SAF blending percentage over total jet fuel for years 2022 to 2030.[@eib2020] The values are provided based on the 3 forecast scenarios proposed by the EUROCONTROL Aviation Outlook 2050.[@aviation:outlook2022] Namely:
*   The *BASE* is the value and date proposed by Annex I of the [ReFuelEU Aviation](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52021PC0561) proposal.
*   More optimistic is the *HIGH* scenario which assumes sufficient SAF volumes become available at competitive prices.
*   In the *LOW* scenario, the price of SAF is higher as there are less investments in new technologies or they occur later than in the *BASE* or *HIGH*.

The percentages of SAF provided are based on the following:
*   The series starts with a projection of the 2022 actual SAF blending.
*   Linear interpolation until in 2030 the required 5% of the [ReFuelEU Aviation](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52021PC0561) is met.

Other underlying assumptions worth mentioning are:
*   The regulation imposes obligations only on the fuel suppliers, not on the airlines.
*   Objective Skygreen 2022-2030 [@skygreen2022] assumes that the SAF blending percentages apply to all the airports within the NM area.

## Comments

Sustainable Aviation Fuels (SAF) are relative to conventional aviation fuel and compliant with certain sustainability requirements. The emission reductions are achieved in their production process. SAF have to meet strict fuel specifications and have comparable behaviour to fossil fuel during the combustion process. SAF can be mixed with conventional fossil-based aviation fuel at a blending ration that is dependent on how the fuel is produced Many experts agree that this is the most promising option to reduce aviation emissions in the short to medium term.

The [ReFuelEU Aviation](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52021PC0561) initiative - put forward by the European Commission in the [Fit for 55 package](https://ec.europa.eu/commission/presscorner/detail/en/IP_21_3541) - imposes a blending obligation on fuel suppliers. As of 2025, the aviation fuel made avilable to EU airports should contain a series of percentages of SAF blending that will have to be met at specific years.

For further research, we invite you to visit the work of our colleagues at the EUROCONTROL Aviation Sustainability Unit.[@aiuportal]

## When to use the input?

This input can be used when dealing with environmentally related assessments. at EUROCONTROL we have used this SAF blending for the traffic forecast in the EUROCONTROL Aviation Outlook 2050[@aviation:outlook2022] and for the Objective Skygreen 2022-2030[@skygreen2022] exploring the economics of aviation decarbonisation towards the 2030 Green Deal milestone.

## References
