# Transit time {#sec-transit-time}

## EUROCONTROL Recommended Values

The transit time per ANSP represents the average time flown by aircraft controlled 
in its airspace over a year. @tbl-transit-time provides the average transit time 
(expressed in minutes) per ANSP in 2024. The data that was used to build this table,
as well as the most recent data, can be accessed on the data section of the [Aviation Intelligence Portal](https://ansperformance.eu/dashboard/stakeholder/ansp/ansp_db/) (which also contains data at ACC level).

```{r}
#| label: tbl-transit-time
#| tbl-cap: Average transit time per country in 2024

library(readxl)
library(dplyr)
library(gt)

read_xlsx(here::here("data", "transit_time.xlsx")) %>%
  gt() %>%
  cols_label(
    ansp = "ANSP",
    minutes = "Transit time (min)"
  ) %>%
  fmt_number(
    columns = c(minutes),
    decimals = 0
  ) %>%
  cols_align(
    align = "center",
    columns = minutes
  ) %>% 
  tab_options(
    table.width = pct(100)
   ) %>% 
   cols_width(
    ansp ~ pct(50),
    minutes ~ pct(50)
  ) %>% 
  tab_options(
    column_labels.font.weight = "bold"
  ) %>%
   tab_source_note(
    source_note = md("*Source: [ACE Benchmarking Report 2026](https://www.eurocontrol.int/publication/air-traffic-management-cost-effectiveness-ace-benchmarking-report-2026-edition)*")
  )
```

This metric is the ratio between the total flight hours controlled and the number
of IFR movements controlled, where:

* Total IFR flight-hours controlled is the sum of the flight-hours controlled 
  over the year by the ANSP. For a given flight, the flight-hours controlled are 
  computed using information available in the Network Manager database as the 
  difference between the exit time and the entry time in the controlled airspace.
  
* IFR movements controlled is the number of flights that have been controlled 
  ver the year by the ANSP as reported by EUROCONROL Performance Review Unit (PRU).
  
The data was recorded by the Network Manager for the 38 main ANSPs operating in
Europe. In @fig-transit-time, the range of transit time values for the ANSPs 
considered above can be observed. The European average in terms of flight time 
is 25 minutes per ANSP.

![Average transit time per ANSP in 2024 (continental only) [@ace:2026]](../figures/transit_time.svg){#fig-transit-time fig-align=center}

## When to use the input?

This input is recommended for those projects where the flying time in a given 
ANSP is key to the assessment. As an example, it has previously been used for
several CNS-related studies, in particular when studying the cost of communication 
services that depend on connection times.

## Related inputs

@sec-medium-term-capacity-planning [Medium-term capacity planning](#sec-medium-term-capacity-planning)

